# Name of the pipeline:
pipeline: "pipeline-evaluation-dmel"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "evaluation"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms.git"

## Pipeline-specific parameters:

# Input genome
genome_fasta: "evaluation/pipeline-evaluation-dmel/data/Drosophila_melanogaster.BDGP6.28.dna.toplevel.fa"

existing_annotation: "evaluation/pipeline-evaluation-dmel/data/Drosophila_melanogaster.BDGP6.28.99.gff3"

# cDNA or direct RNA reads in fastq format
reads_fastq: "evaluation/pipeline-evaluation-dmel/data/ERR3588905_1.fastq"

# The path above is a directory, find and concatenate fastq files:
concatenate: false

# Not used at the moment:
read_qc: false

run_pychopper: true

pychopper_opts: ""

# Extra option passed to minimap2 when generating index
minimap_index_opts: "-k14"

# Extra options passed to minimap2
minimap2_opts: "-uf "
# Add this for SIRV data:
# "--splice-flank=no"

# Minmum mapping quality
minimum_mapping_quality: 40

poly_context: 24

max_poly_run: 8

bundle_min_reads: 50000

use_guide_annotation: true

stringtie_opts: " --conservative "

gffcompare_opts: " -R "

# Threads
threads: 50

